[book]
authors = ["unknown"]
language = "en"
multilingual = false
src = "{{.Name}}"
title = "{{.Name}}"

[build]
build-dir = "public"

[output.html]
no-section-label = true

[output.html.search]
limit-results = 15
teaser-word-count = 50
use-boolean-and = true

[output.html.fold]
enable = true
