package cmd

import (
	"fmt"

	"github.com/mlange-42/modo/internal/document"
	"github.com/mlange-42/modo/internal/format"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func cleanCommand() (*cobra.Command, error) {
	v := viper.New()
	var config string

	root := &cobra.Command{
		Use:   "clean [PATH]",
		Short: "Remove Markdown and test files generated by Modo",
		Long: `Remove Markdown and test files generated by Modo.

Complete documentation at https://mlange-42.github.io/modo/`,
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if err := checkConfigFile(config); err != nil {
				return err
			}
			if err := mountProject(v, config, args); err != nil {
				return err
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			cliArgs, err := document.ConfigFromViper(v)
			if err != nil {
				return err
			}
			return runClean(cliArgs)
		},
	}

	root.Flags().StringVarP(&config, "config", "c", defaultConfigFile, "Config file in the working directory to use")

	root.Flags().SortFlags = false
	root.MarkFlagFilename("config", "yaml")

	return root, nil
}

func runClean(args *document.Config) error {
	if args.OutputDir == "" {
		return fmt.Errorf("no output path given")
	}

	formatter, err := format.GetFormatter(args.RenderFormat)
	if err != nil {
		return err
	}

	return formatter.Clean(args.OutputDir, args.TestOutput)
}
