name: Publish

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  publish:
    name: Run tests
    runs-on: ubuntu-latest
    steps:    
      - name: Install magic CLI
        run: |
          curl -ssL https://magic.modular.com | bash
          source /home/runner/.bash_profile
      - name: Clone stdlib
        run: |
          git clone https://github.com/modularml/mojo.git --depth=1
      - name: Install mojo and dependencies
        run: |
          cd mojo
          source /home/runner/.bash_profile
          magic install
      - name: Generate JSON docs
        run: |
          mojo doc -o ../stdlib.json stdlib/src
          cd ..
