name: Upload to TestPyPI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  publish:
    name: Generate and publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Modo
        uses: actions/checkout@v3
      - name: Setup PYthon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install --upgrade build twine
      - name: Build wheel
        run: |
          python -m build
      - name: Upload to TestPyPI
        run: |
          python -m twine upload --verbose --skip-existing -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }} dist/*
